networks:
  goodcare:
    driver: bridge
volumes:
  goodcare_db_volume:

services:
  db:
    image: postgres
    container_name: goodcare-postgresql-dev
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pwd}
      POSTGRES_DB: ${DB_NAME:-postgres}
    volumes:
      - goodcare_db_volume:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
    networks:
      - goodcare

  rabbitmq:
    image: rabbitmq:alpine
    container_name: goodcare-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USERNAME:-user}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD:-pwd}
    ports:
      - ${RMQ_API_PORT:-5672}:5672
      - ${RMQ_HTTP_API_PORT:-15672}:15672

  react:
    build:
      context: ../goodcare_react_app
      dockerfile: Dockerfile
    image: goodcare-react-app-image
    container_name: goodcare-react-app-dev
    ports:
      - ${REACT_PORT:-80}:80
    networks:
      - goodcare

  php:
    build:
      context: ../goodcare_php_rest_api
      dockerfile: Dockerfile
    image: goodcare-php-api-image
    container_name: goodcare-php-api-dev
    environment:
      DB_CONNECTION: ${DB_CONNECTION:-pgsql}
      DB_USERNAME: ${DB_USERNAME:-user}
      DB_PASSWORD: ${DB_PASSWORD:-pwd}
      DB_NAME: ${DB_NAME:-postgres}
      DB_PORT: 5432
      DB_HOST: db
      TOKEN_KEY: ${TOKEN_KEY:-secret_key}
    ports:
      - ${PHP_PORT:-8000}:8000
    networks:
      - goodcare